# Generated by Django 3.1.3 on 2020-12-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_borrow_borrowbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='ordered',
            new_name='borrowed',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='ordered_date',
            new_name='borrowed_date',
        ),
    ]
