# Generated by Django 3.1.3 on 2021-01-21 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0008_auto_20210121_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 2, 4, 13, 56, 14, 531987, tzinfo=utc)),
        ),
    ]
