# Generated by Django 3.1.1 on 2021-01-29 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0014_auto_20210126_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 2, 12, 16, 7, 23, 147413, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
