# Generated by Django 3.1.6 on 2021-02-09 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0018_auto_20210204_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 2, 23, 13, 50, 2, 856097, tzinfo=utc)),
        ),
    ]
